// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA26EMp3635qzY7edzqfH4mvPkzaryBJh8',
    appId: '1:842174780794:android:007320e9474dc03903f2c3',
    messagingSenderId: '842174780794',
    projectId: 'flutterapitest123-e4e6a',
    databaseURL: 'https://flutterapitest123-e4e6a-default-rtdb.firebaseio.com',
    storageBucket: 'flutterapitest123-e4e6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJd1CDtGiLvkk5zE4Hp7VPly1dFLXO7fE',
    appId: '1:842174780794:ios:47a19328af97598d03f2c3',
    messagingSenderId: '842174780794',
    projectId: 'flutterapitest123-e4e6a',
    databaseURL: 'https://flutterapitest123-e4e6a-default-rtdb.firebaseio.com',
    storageBucket: 'flutterapitest123-e4e6a.firebasestorage.app',
    iosBundleId: 'com.mychatapps.mychat',
  );
}
